# Generated by Django 4.2.16 on 2026-06-14 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importreport',
            name='log_data',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('rejected_rows', models.IntegerField(default=0)),
                ('corrected_rows', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='expenses.group')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='expenses.group')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_row_number', models.IntegerField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('corrected_value', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('imported', 'Imported'), ('corrected', 'Corrected'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='flagged', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='expenses.import')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.category'),
        ),
        migrations.AddField(
            model_name='importreport',
            name='import_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='expenses.import'),
        ),
    ]
